// Demo for unsorted single linked list of integers: functional version
// NOTE:
// selection of iterative or recursive version is solely made by linking
// the appropriate object files
//

#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>

#include "singleLinkedIntList_functional.h"
#include "dumpListForDot.h"

// ----------------------------------------------------------------
// MAIN
// ----------------------------------------------------------------

int main () {
  node_t* mylist=NULL;
  int value;

  // ---------------------------------------
  // Demo 1: insert at the front
  printf("\nDemo 1\n");
  mylist = list_insert_front(mylist, 10);
  mylist = list_insert_front(mylist, 11);
  mylist = list_insert_front(mylist, 12);
  mylist = list_insert_front(mylist, 13);
  mylist = list_insert_front(mylist, 14);
  mylist = list_insert_front(mylist, 15);

  // Dump the list
  printf("List generated by list_insert_front\n");
  list_dump(mylist);

  // Free the list; assignment sets anchor to NULL
  mylist = list_free(mylist);

  // ---------------------------------------
  // Demo 2: insert at the end
  printf("\nDemo 2\n");
  mylist = list_insert_end(mylist, 10);
  mylist = list_insert_end(mylist, 11);
  mylist = list_insert_end(mylist, 12);
  mylist = list_insert_end(mylist, 13);
  mylist = list_insert_end(mylist, 14);
  mylist = list_insert_end(mylist, 15);

  // Dump the list
  printf("List generated by list_insert_end\n");
  list_dump(mylist);

  // Free the list; assignment sets anchor to NULL
  mylist = list_free(mylist);

  // ---------------------------------------
  // Demo 3:
  // - check if node with specified data is contained in the list
  printf("\nDemo 3\n");
  mylist = list_insert_end(mylist, 10);
  mylist = list_insert_end(mylist, 12);
  mylist = list_insert_end(mylist, 14);
  mylist = list_insert_end(mylist, 14);
  mylist = list_insert_end(mylist, 16);
  mylist = list_insert_end(mylist, 15);

  // Dump the list
  printf("List generated by list_insert_end\n");
  list_dump(mylist);

  value = 11;
  printf("\n");
  if (list_contains(mylist,value)){
    printf("Value %d is contained in list\n", value);
  } else {
    printf("Value %d is not contained in list\n", value);
  }

  // Use ternary conditional expressione _?_:_
  value = 14;
  printf("Value %d is %s in list\n",value,
      list_contains(mylist,value)?"contained":"not contained");

  // Use ternary conditional expressione _?_:_
  value = 15;
  printf("Value %d is %s in list\n",value,
      list_contains(mylist,value)?"contained":"not contained");

  // Free the list; assignment sets anchor to NULL
  mylist = list_free(mylist);

  // ---------------------------------------
  // Demo 4:
  // - delete first occurrence of a node with specified data
  // - delete all occurrences of a node with specified data
  printf("\nDemo 4\n");
  mylist = list_insert_end(mylist, 14);
  mylist = list_insert_end(mylist, 12);
  mylist = list_insert_end(mylist, 14);
  mylist = list_insert_end(mylist, 14);
  mylist = list_insert_end(mylist, 16);
  mylist = list_insert_end(mylist, 17);

  // Dump the list
  printf("List generated by list_insert_end\n");
  list_dump(mylist);

  // Demo of the goody
  list_dump_as_graph(mylist, "demo4_START.dot");

  // Delete first occurrence of value 
  value=14;
  mylist = list_delete_first(mylist, value);

  // Dump the list
  printf("\n");
  printf("List after deleting first occurrence of value %d\n", value);
  list_dump(mylist);

  // Delete all occurrences of value 
  value=14;
  mylist = list_delete_all(mylist, value);

  // Dump the list
  printf("\n");
  printf("List after deleting all occurrences of value %d\n", value);
  list_dump(mylist);

  // Demo of the goody
  list_dump_as_graph(mylist, "demo4_END.dot");

  // Free the list; assignment sets anchor to NULL
  mylist = list_free(mylist);

  // ---------------------------------------
  // Demo 5: same as 3 but different data
  // - delete all occurrences of a node with specified data
  //   where node does not occur in the list
  printf("\nDemo 5\n");
  mylist = list_insert_end(mylist, 12);
  mylist = list_insert_end(mylist, 12);
  mylist = list_insert_end(mylist, 11);
  mylist = list_insert_end(mylist, 16);
  mylist = list_insert_end(mylist, 16);
  mylist = list_insert_end(mylist, 17);

  // Dump the list
  printf("List generated by list_insert_end\n");
  list_dump(mylist);

  // Delete all occurrences of value 
  value=14;
  mylist = list_delete_all(mylist, value);

  // Dump the list
  printf("\n");
  printf("List after deleting all occurrences of value %d,\n"
      "which is not contained in the list\n", value);
  list_dump(mylist);

  // Free the list; assignment sets anchor to NULL
  mylist = list_free(mylist);

  // ---------------------------------------
  // Demo 6:
  // - get head elemnt of list
  // - get tail elemnt of list
  // - delete head element of list
  // - delete tail element of list
  printf("\nDemo 6\n");
  mylist = list_insert_front(mylist, 11);
  mylist = list_insert_front(mylist, 12);
  mylist = list_insert_front(mylist, 13);
  mylist = list_insert_front(mylist, 14);
  mylist = list_insert_front(mylist, 15);
  mylist = list_insert_front(mylist, 16);

  // Dump the list
  printf("List generated by list_insert_front\n");
  list_dump(mylist);

  // get data of head element
  printf("\n");
  printf("Data of head element is %d\n", list_get_head(mylist));

  // get data of tail element
  printf("Data of tail element is %d\n", list_get_tail(mylist));

  // - delete head element of list
  mylist = list_remove_head(mylist);

  // Dump the list
  printf("\n");
  printf("List after deleting head element of list\n");
  list_dump(mylist);

  // - delete tail element of list
  mylist = list_remove_tail(mylist);

  // Dump the list
  printf("\n");
  printf("List after deleting tail element of list\n");
  list_dump(mylist);

  // Demo of the goody
  list_dump_as_graph(mylist, "demo6_END.dot");

  // Free the list; assignment sets anchor to NULL
  mylist = list_free(mylist);

  // ---------------------------------------
  return EXIT_SUCCESS;
}
